<#
.SYNOPSIS
    Auto-generate the tool quick-reference table from [YIUIMCPTools("name","desc")]
    attributes and inject it into skills/yiuimcp/SKILL.md.

.DESCRIPTION
    Scans every .cs under Editor/UnityMCP/Tools, extracts tool name + description,
    splits them into two groups (Basic / YIUI ops), builds a markdown table and
    replaces the content between <!-- AUTOGEN:TOOLS:START --> and ...:END --> in
    SKILL.md. Re-run after adding/changing tools so the doc never goes stale.

    NOTE: keep this script PURE ASCII. Windows PowerShell 5.1 parses a no-BOM .ps1
    using the system ANSI codepage (GBK on Chinese Windows); any non-ASCII literal
    OR comment can be mis-decoded and break parsing. The Chinese tool descriptions
    are fine because they are read from the .cs files with -Encoding UTF8.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File ".\Packages\cn.etetet.yiuimcp\Config\gen-skill-tools.ps1"
#>

$ErrorActionPreference = 'Stop'

$pkgRoot   = Split-Path -Parent $PSScriptRoot
$toolsDir  = Join-Path $pkgRoot 'Editor/UnityMCP/Tools'
$skillFile = Join-Path $pkgRoot 'skills/yiuimcp/SKILL.md'

if (-not (Test-Path $toolsDir))  { throw "tools dir not found: $toolsDir" }
if (-not (Test-Path $skillFile)) { throw "SKILL.md not found: $skillFile" }

# 1. Scan all [YIUIMCPTools("name","desc")]
$rx = [regex]'\[YIUIMCPTools\("(?<name>[^"]+)",\s*"(?<desc>[^"]+)"\)\]'
$tools = @{}
Get-ChildItem -Path $toolsDir -Recurse -Filter *.cs | ForEach-Object {
    $text = Get-Content -Raw -Encoding UTF8 $_.FullName
    foreach ($m in $rx.Matches($text)) {
        $tools[$m.Groups['name'].Value] = $m.Groups['desc'].Value
    }
}

if ($tools.Count -eq 0) { throw "no [YIUIMCPTools] found - check regex / dir" }

# 2. Group: non-YIUI-prefixed = Basic, rest = YIUI ops
$basic = $tools.Keys | Where-Object { $_ -notlike 'YIUI*' } | Sort-Object
$yiui  = $tools.Keys | Where-Object { $_ -like 'YIUI*'  } | Sort-Object

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("")
[void]$sb.AppendLine("_$($tools.Count) tools - auto-generated by gen-skill-tools.ps1, do not edit by hand_")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("**Basic (compile / console / play / menu)**")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("| Tool | Desc |")
[void]$sb.AppendLine("|---|---|")
foreach ($n in $basic) { [void]$sb.AppendLine("| ``$n`` | $($tools[$n]) |") }
[void]$sb.AppendLine("")
[void]$sb.AppendLine("**YIUI ops (create / node / layout / binding / capture)**")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("| Tool | Desc |")
[void]$sb.AppendLine("|---|---|")
foreach ($n in $yiui) { [void]$sb.AppendLine("| ``$n`` | $($tools[$n]) |") }

$table = $sb.ToString().TrimEnd()

# 3. Splice content between AUTOGEN markers in SKILL.md.
#    Use plain Substring (NOT [regex]::Replace) so $ / backtick chars in the table
#    are never interpreted as .NET regex replacement metacharacters.
$startMark = '<!-- AUTOGEN:TOOLS:START -->'
$endMark   = '<!-- AUTOGEN:TOOLS:END -->'
$content   = Get-Content -Raw -Encoding UTF8 $skillFile

$iStart = $content.IndexOf($startMark)
$iEnd   = $content.IndexOf($endMark)
if ($iStart -lt 0 -or $iEnd -lt 0 -or $iEnd -lt $iStart) {
    throw "AUTOGEN markers not found / out of order in SKILL.md"
}

$pre  = $content.Substring(0, $iStart + $startMark.Length)
$post = $content.Substring($iEnd)
$new  = $pre + "`n" + $table + "`n" + $post

# Write back as UTF-8 (no BOM)
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($skillFile, $new, $utf8NoBom)

Write-Host "OK: basic=$($basic.Count) yiui=$($yiui.Count) total=$($tools.Count) -> $skillFile"
